# Generated by Django 3.0.5 on 2020-05-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200504_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.BigIntegerField(default='0000000000', max_length=10)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
