# Generated by Django 3.0.5 on 2020-05-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default='0000000000', max_length=10),
        ),
    ]
